//! Renders `api_docs()` as a Luau definition file (`maki.d.luau`) for
//! `lute check`. Every function is `@checked`, so nonstrict mode reports calls
//! with arguments of the wrong type. Nonstrict can't negate table or function
//! types, so those and arrays are `any`, and so are userdata classes for now.

use std::collections::BTreeSet;

use maki_lua::docs::{DocKind, FnDoc, ModuleDoc, api_docs};

const HEADER: &str = "-- Generated by maki-docgen from the `maki` API docs. Do not edit.\n";
const ROOT: &str = "maki";
const INDENT: &str = "  ";
const ANY: &str = "any";
const REST: &str = "...";
const ANY_REST: &str = "...any";
const NIL: &str = "nil";
const INTEGER: &str = "integer";
const NUMBER: &str = "number";
const PRIMITIVES: [&str; 4] = ["string", "boolean", "buffer", "true"];
const OPAQUE: [&str; 5] = [ANY, "table", "function", "userdata", "LuaCtx"];

pub fn generate() -> String {
    let docs = api_docs();
    let mut out = format!("{HEADER}\ndeclare {ROOT}: ");
    push_table(&mut out, ROOT, &docs);
    out.push('\n');
    out
}

fn push_table(out: &mut String, path: &str, docs: &[&ModuleDoc]) {
    let depth = path.matches('.').count();
    let indent = INDENT.repeat(depth + 1);
    out.push_str("{\n");
    for f in docs.iter().filter(|m| m.name == path).flat_map(|m| m.fns) {
        out.push_str(&format!(
            "{indent}{}: @checked {},\n",
            f.name,
            signature(path, f, docs)
        ));
    }
    let children: BTreeSet<&str> = docs
        .iter()
        .filter(|m| m.kind == DocKind::Table)
        .filter_map(|m| m.name.rsplit_once('.'))
        .filter(|(parent, _)| *parent == path)
        .map(|(_, key)| key)
        .collect();
    for key in children {
        out.push_str(&format!("{indent}{key}: "));
        push_table(out, &format!("{path}.{key}"), docs);
        out.push_str(",\n");
    }
    out.push_str(&format!("{}}}", INDENT.repeat(depth)));
}

fn signature(path: &str, f: &FnDoc, docs: &[&ModuleDoc]) -> String {
    let resolve = |ty: &str| match ty {
        REST => ANY_REST.to_owned(),
        _ => luau_type(ty, docs)
            .unwrap_or_else(|| panic!("`{path}.{}`: no Luau type for `{ty}`", f.name)),
    };
    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| {
            let ty = resolve(p.ty);
            match p.name.trim_matches(['{', '}', '?']) {
                REST => format!("{REST}{ty}"),
                name => format!("{name}: {ty}"),
            }
        })
        .collect();
    let returns: Vec<String> = f
        .returns
        .strip_prefix('(')
        .and_then(|r| r.split_once(')'))
        .map_or(f.returns, |(types, _)| types)
        .split_terminator(", ")
        .map(resolve)
        .collect();
    format!("({}) -> ({})", params.join(", "), returns.join(", "))
}

/// Maps a doc type such as `string|nil` or `table?` to Luau, `None` if unknown.
fn luau_type(ty: &str, docs: &[&ModuleDoc]) -> Option<String> {
    let (ty, mut nullable) = ty
        .strip_suffix('?')
        .map_or((ty, false), |base| (base, true));
    let mut members = Vec::new();
    let mut opaque = false;
    for atom in ty.split('|') {
        match atom {
            NIL => nullable = true,
            INTEGER => members.push(NUMBER),
            _ if PRIMITIVES.contains(&atom) => members.push(atom),
            _ if is_opaque(atom, docs) => opaque = true,
            _ => return None,
        }
    }
    if opaque {
        return Some(ANY.to_owned());
    }
    let union = members.join(" | ");
    Some(if nullable { format!("{union}?") } else { union })
}

/// Tables, functions, arrays and userdata classes such as `Node` or `maki.net.Conn`.
fn is_opaque(atom: &str, docs: &[&ModuleDoc]) -> bool {
    OPAQUE.contains(&atom)
        || docs.iter().any(|m| {
            m.kind == DocKind::Class
                && (m.name == atom || m.name.rsplit_once('.').is_some_and(|(_, n)| n == atom))
        })
        || atom
            .strip_suffix("[]")
            .is_some_and(|element| luau_type(element, docs).is_some())
}

#[cfg(test)]
mod tests {
    use maki_lua::docs::api_docs;
    use test_case::test_case;

    use super::luau_type;

    #[test_case("integer?", Some("number?") ; "optional")]
    #[test_case("string|nil", Some("string?") ; "nil_union_is_optional")]
    #[test_case("table?", Some("any") ; "table_is_any")]
    #[test_case("string|string[]", Some("any") ; "array_is_any")]
    #[test_case("Node|nil", Some("any") ; "class_is_any")]
    #[test_case("maki.net.Conn?", Some("any") ; "class_by_full_name_is_any")]
    #[test_case("strng", None ; "unknown_type")]
    #[test_case("Nod", None ; "unknown_class")]
    #[test_case("Nod[]", None ; "unknown_array_element")]
    fn maps_doc_types(ty: &str, expected: Option<&str>) {
        assert_eq!(luau_type(ty, &api_docs()).as_deref(), expected);
    }
}
